[project]
name = "benjaminschmidt-github-io"
version = "1.0.0"
description = "The code for the personal website of Benjamin Schmidt using Django"
readme = "README.md"
requires-python = "==3.9.24"
dependencies = [
    "django==4.1.7",
    "pillow==9.4.0",
    "tzdata==2022.7",
]
